# Linear Disriminant Analysis

*EXTRA*

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns

In [32]:
from sklearn import datasets
iris = datasets.load_iris()

In [33]:
df = pd.DataFrame(iris.data, columns = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width'])
df["target"] = iris.target

# X and y


* extra .. sometimes you can see .values as in the example below - this is just how we obtain the numpy array data type instead of the pandas series. (When working with neural networks it might be better to work with numpy array) 

In [34]:
y = df["target"].values
X = df[['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width']].values

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y) 

# build the model

In [36]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()
clf.fit(X, y)  

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [37]:
clf.score(x_train,y_train)

0.9732142857142857

In [38]:
clf.score(x_test,y_test)

1.0

# for prediction

In [40]:
y_pred = clf.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[14  0  0]
 [ 0 11  0]
 [ 0  0 13]]
Accuracy1.0
